"use server"

import { createClient } from "@/lib/supabase/server"
import { revalidatePath } from "next/cache"

// Types
export type Class = {
  id: string
  teacher_id: string
  name: string
  subject: string
  join_code: string
  created_at: string
  updated_at: string
  student_count?: number
}

export type ClassStudent = {
  id: string
  email: string
  full_name: string | null
  joined_at: string
}

export type Enrollment = {
  id: string
  class_id: string
  student_id: string
  joined_at: string
}

// =====================================================
// Teacher Actions
// =====================================================

/**
 * Creates a new class for the logged-in teacher
 * Returns the new class object including the auto-generated join_code
 */
export async function createClass(name: string, subject: string = "Maths") {
  const supabase = await createClient()
  
  // Get current user
  const { data: { user }, error: userError } = await supabase.auth.getUser()
  
  if (userError || !user) {
    return { 
      success: false, 
      error: "You must be logged in to create a class" 
    }
  }

  // Verify user is a teacher
  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single()

  if (profile?.role !== "teacher") {
    return { 
      success: false, 
      error: "Only teachers can create classes" 
    }
  }

  // Create the class (join_code will be auto-generated by trigger)
  const { data: newClass, error: insertError } = await supabase
    .from("classes")
    .insert({
      teacher_id: user.id,
      name: name.trim(),
      subject: subject.trim(),
      join_code: "" // Will be replaced by trigger
    })
    .select()
    .single()

  if (insertError) {
    console.error("Error creating class:", insertError)
    return { 
      success: false, 
      error: "Failed to create class. Please try again." 
    }
  }

  revalidatePath("/dashboard")
  revalidatePath("/dashboard/students")

  return { 
    success: true, 
    data: newClass as Class 
  }
}

/**
 * Gets all classes owned by the logged-in teacher
 * Includes student count for each class
 */
export async function getClassList() {
  const supabase = await createClient()
  
  const { data: { user }, error: userError } = await supabase.auth.getUser()
  
  if (userError || !user) {
    return { 
      success: false, 
      error: "You must be logged in" 
    }
  }

  // Get classes with student count
  const { data: classes, error: classesError } = await supabase
    .from("classes")
    .select(`
      *,
      enrollments(count)
    `)
    .eq("teacher_id", user.id)
    .order("created_at", { ascending: false })

  if (classesError) {
    console.error("Error fetching classes:", classesError)
    return { 
      success: false, 
      error: "Failed to fetch classes" 
    }
  }

  // Transform the data to include student_count
  const transformedClasses = classes.map(cls => ({
    ...cls,
    student_count: Array.isArray(cls.enrollments) ? cls.enrollments.length : 0,
    enrollments: undefined // Remove raw enrollments data
  }))

  return { 
    success: true, 
    data: transformedClasses as Class[]
  }
}

/**
 * Gets the list of students enrolled in a specific class
 * Returns student info from profiles table
 */
export async function getClassStudents(classId: string) {
  const supabase = await createClient()
  
  const { data: { user }, error: userError } = await supabase.auth.getUser()
  
  if (userError || !user) {
    return { 
      success: false, 
      error: "You must be logged in" 
    }
  }

  // Verify the class belongs to this teacher
  const { data: classData, error: classError } = await supabase
    .from("classes")
    .select("teacher_id")
    .eq("id", classId)
    .single()

  if (classError || !classData) {
    return { 
      success: false, 
      error: "Class not found" 
    }
  }

  if (classData.teacher_id !== user.id) {
    return { 
      success: false, 
      error: "You don't have permission to view this class" 
    }
  }

  // Get students enrolled in this class
  const { data: enrollments, error: enrollmentsError } = await supabase
    .from("enrollments")
    .select("student_id, joined_at")
    .eq("class_id", classId)
    .order("joined_at", { ascending: true })

  if (enrollmentsError) {
    console.error("Error fetching enrollments:", enrollmentsError)
    return { 
      success: false, 
      error: "Failed to fetch students" 
    }
  }

  // Get unique student IDs
  const studentIds = enrollments?.map(e => e.student_id) || []
  
  if (studentIds.length === 0) {
    return { success: true, data: [] }
  }

  // Fetch student profiles separately
  const { data: profiles, error: profilesError } = await supabase
    .from("profiles")
    .select("id, email, full_name")
    .in("id", studentIds)

  if (profilesError) {
    console.error("Error fetching student profiles:", profilesError)
    return { 
      success: false, 
      error: "Failed to fetch student profiles" 
    }
  }

  // Create a map for quick profile lookup
  const profileMap = new Map(profiles?.map(p => [p.id, p]) || [])

  // Transform the data
  const students = enrollments
    .map(e => {
      const profile = profileMap.get(e.student_id)
      if (!profile) return null
      return {
        id: profile.id,
        email: profile.email,
        full_name: profile.full_name,
        joined_at: e.joined_at
      }
    })
    .filter((s): s is ClassStudent => s !== null)

  return { 
    success: true, 
    data: students as ClassStudent[]
  }
}

/**
 * Deletes a class (only if owned by current teacher)
 */
export async function deleteClass(classId: string) {
  const supabase = await createClient()
  
  const { data: { user }, error: userError } = await supabase.auth.getUser()
  
  if (userError || !user) {
    return { 
      success: false, 
      error: "You must be logged in" 
    }
  }

  // Delete the class (RLS ensures only owner can delete)
  const { error: deleteError } = await supabase
    .from("classes")
    .delete()
    .eq("id", classId)
    .eq("teacher_id", user.id)

  if (deleteError) {
    console.error("Error deleting class:", deleteError)
    return { 
      success: false, 
      error: "Failed to delete class" 
    }
  }

  revalidatePath("/dashboard")
  revalidatePath("/dashboard/students")

  return { success: true }
}

/**
 * Removes a student from a class
 */
export async function removeStudentFromClass(classId: string, studentId: string) {
  const supabase = await createClient()
  
  const { data: { user }, error: userError } = await supabase.auth.getUser()
  
  if (userError || !user) {
    return { 
      success: false, 
      error: "You must be logged in" 
    }
  }

  // Verify the class belongs to this teacher
  const { data: classData, error: classError } = await supabase
    .from("classes")
    .select("teacher_id")
    .eq("id", classId)
    .single()

  if (classError || !classData || classData.teacher_id !== user.id) {
    return { 
      success: false, 
      error: "You don't have permission to modify this class" 
    }
  }

  // Remove the enrollment
  const { error: deleteError } = await supabase
    .from("enrollments")
    .delete()
    .eq("class_id", classId)
    .eq("student_id", studentId)

  if (deleteError) {
    console.error("Error removing student:", deleteError)
    return { 
      success: false, 
      error: "Failed to remove student" 
    }
  }

  revalidatePath("/dashboard/students")

  return { success: true }
}

// =====================================================
// Student Actions
// =====================================================

/**
 * Allows a student to join a class using a join code
 */
export async function joinClass(code: string) {
  const supabase = await createClient()
  
  const { data: { user }, error: userError } = await supabase.auth.getUser()
  
  if (userError || !user) {
    return { 
      success: false, 
      error: "You must be logged in to join a class" 
    }
  }

  // Verify user is a student
  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single()

  if (profile?.role !== "student") {
    return { 
      success: false, 
      error: "Only students can join classes" 
    }
  }

  // Validate and find the class using RPC function (bypasses RLS)
  const joinCode = code.trim().toUpperCase()
  
  const { data: classData, error: classError } = await supabase
    .rpc("lookup_class_by_join_code", { p_join_code: joinCode })
    .single()

  if (classError || !classData) {
    console.error("Error finding class with join code:", classError)
    return { 
      success: false, 
      error: "Invalid join code. Please check and try again." 
    }
  }

  // Type assertion for RPC result
  const foundClass = classData as { id: string; name: string; subject: string; teacher_id: string }

  // Check if already enrolled
  const { data: existingEnrollment } = await supabase
    .from("enrollments")
    .select("id")
    .eq("class_id", foundClass.id)
    .eq("student_id", user.id)
    .single()

  if (existingEnrollment) {
    return { 
      success: false, 
      error: "You are already enrolled in this class" 
    }
  }

  // Create enrollment
  const { error: enrollError } = await supabase
    .from("enrollments")
    .insert({
      class_id: foundClass.id,
      student_id: user.id
    })

  if (enrollError) {
    console.error("Error joining class:", enrollError)
    return { 
      success: false, 
      error: "Failed to join class. Please try again." 
    }
  }

  revalidatePath("/dashboard")

  return { 
    success: true, 
    data: foundClass 
  }
}

/**
 * Gets all classes the logged-in student is enrolled in
 */
export async function getEnrolledClasses() {
  const supabase = await createClient()
  
  const { data: { user }, error: userError } = await supabase.auth.getUser()
  
  if (userError || !user) {
    return { 
      success: false, 
      error: "You must be logged in" 
    }
  }

  // Get enrolled classes
  const { data: enrollments, error: enrollmentsError } = await supabase
    .from("enrollments")
    .select(`
      joined_at,
      classes!inner(
        id,
        name,
        subject,
        teacher_id
      )
    `)
    .eq("student_id", user.id)
    .order("joined_at", { ascending: false })

  if (enrollmentsError) {
    console.error("Error fetching enrolled classes:", enrollmentsError)
    return { 
      success: false, 
      error: "Failed to fetch classes" 
    }
  }

  // Transform the data
  const classes = enrollments
    .filter(e => e.classes)
    .map(e => ({
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      ...(e.classes as any),
      joined_at: e.joined_at
    }))

  return { 
    success: true, 
    data: classes 
  }
}

/**
 * Allows a student to leave a class
 */
export async function leaveClass(classId: string) {
  const supabase = await createClient()
  
  const { data: { user }, error: userError } = await supabase.auth.getUser()
  
  if (userError || !user) {
    return { 
      success: false, 
      error: "You must be logged in" 
    }
  }

  // Remove the enrollment
  const { error: deleteError } = await supabase
    .from("enrollments")
    .delete()
    .eq("class_id", classId)
    .eq("student_id", user.id)

  if (deleteError) {
    console.error("Error leaving class:", deleteError)
    return { 
      success: false, 
      error: "Failed to leave class" 
    }
  }

  revalidatePath("/dashboard")

  return { success: true }
}
