import { Question } from "@/components/question-card"

// Re-export the Question type for convenience
export type { Question }

export const mockQuestions: Question[] = [
  {
    id: "Q001",
    questionText: "Solve the quadratic equation: x² + 5x + 6 = 0",
    markSchemeText: "Factorize to (x + 2)(x + 3) = 0. Therefore x = -2 or x = -3. (2 marks: 1 for method, 1 for both solutions)",
    tier: "Foundation",
    level: "GCSE",
    topic: "Algebra",
    learningObjective: "Solve quadratic equations by factorization",
    calculatorAllowed: false,
    difficulty: 2,
    marks: 2,
  },
  {
    id: "Q002",
    questionText: "Calculate the area of a circle with radius 7cm. Give your answer in terms of π.",
    markSchemeText: "A = πr². A = π × 7² = 49π cm². (2 marks: 1 for formula, 1 for correct answer)",
    tier: "Foundation",
    level: "GCSE",
    topic: "Geometry",
    learningObjective: "Calculate the area of a circle using the formula A = πr²",
    calculatorAllowed: true,
    difficulty: 1,
    marks: 2,
  },
  {
    id: "Q003",
    questionText: "Differentiate y = 3x⁴ + 2x² - 5x + 7 with respect to x.",
    markSchemeText: "dy/dx = 12x³ + 4x - 5. (3 marks: 1 for each term differentiated correctly)",
    tier: "Higher",
    level: "A-Level",
    topic: "Calculus",
    learningObjective: "Apply power rule to differentiate polynomial functions",
    calculatorAllowed: false,
    difficulty: 3,
    marks: 3,
  },
  {
    id: "Q004",
    questionText: "A bag contains 5 red balls and 3 blue balls. Two balls are drawn without replacement. Calculate the probability that both balls are red.",
    markSchemeText: "P(1st red) = 5/8. P(2nd red | 1st red) = 4/7. P(both red) = 5/8 × 4/7 = 20/56 = 5/14. (3 marks: 1 for first probability, 1 for conditional probability, 1 for final answer)",
    tier: "Higher",
    level: "GCSE",
    topic: "Probability",
    learningObjective: "Calculate conditional probability without replacement",
    calculatorAllowed: true,
    difficulty: 4,
    marks: 3,
  },
  {
    id: "Q005",
    questionText: "Expand and simplify: (2x + 3)(x - 4)",
    markSchemeText: "2x² - 8x + 3x - 12 = 2x² - 5x - 12. (2 marks: 1 for expansion, 1 for simplification)",
    tier: "Foundation",
    level: "GCSE",
    topic: "Algebra",
    learningObjective: "Expand and simplify brackets using distributive property",
    calculatorAllowed: false,
    difficulty: 2,
    marks: 2,
  },
  {
    id: "Q006",
    questionText: "Find the equation of the line passing through (2, 5) with gradient 3.",
    markSchemeText: "y - y₁ = m(x - x₁). y - 5 = 3(x - 2). y - 5 = 3x - 6. y = 3x - 1. (3 marks: 1 for formula, 1 for substitution, 1 for final answer)",
    tier: "Higher",
    level: "GCSE",
    topic: "Algebra",
    learningObjective: "Find the equation of a line given a point and gradient",
    calculatorAllowed: false,
    difficulty: 3,
    marks: 3,
  },
  {
    id: "Q007",
    questionText: "Calculate the volume of a cylinder with radius 4cm and height 10cm. Give your answer to 2 decimal places.",
    markSchemeText: "V = πr²h = π × 4² × 10 = 160π = 502.65 cm³. (3 marks: 1 for formula, 1 for substitution, 1 for answer to 2dp)",
    tier: "Foundation",
    level: "GCSE",
    topic: "Geometry",
    learningObjective: "Calculate the volume of a cylinder using V = πr²h",
    calculatorAllowed: true,
    difficulty: 2,
    marks: 3,
  },
  {
    id: "Q008",
    questionText: "Solve the simultaneous equations: 2x + y = 10 and x - y = 2",
    markSchemeText: "From equation 2: x = y + 2. Substitute into equation 1: 2(y + 2) + y = 10. 2y + 4 + y = 10. 3y = 6. y = 2. x = 4. (4 marks: 1 for elimination/substitution method, 1 for y, 1 for x, 1 for checking)",
    tier: "Higher",
    level: "GCSE",
    topic: "Algebra",
    learningObjective: "Solve simultaneous linear equations using substitution or elimination",
    calculatorAllowed: false,
    difficulty: 3,
    marks: 4,
  },
  {
    id: "Q009",
    questionText: "A sequence is defined by the nth term formula: 3n + 2. Find the 10th term and the sum of the first 5 terms.",
    markSchemeText: "10th term: 3(10) + 2 = 32. First 5 terms: 5, 8, 11, 14, 17. Sum = 5 + 8 + 11 + 14 + 17 = 55. (3 marks: 1 for 10th term, 1 for listing terms, 1 for sum)",
    tier: "Foundation",
    level: "GCSE",
    topic: "Sequences",
    learningObjective: "Use nth term formula to find specific terms and sums",
    calculatorAllowed: true,
    difficulty: 2,
    marks: 3,
  },
  {
    id: "Q010",
    questionText: "Integrate: ∫(6x² + 4x - 3) dx",
    markSchemeText: "2x³ + 2x² - 3x + C. (3 marks: 1 for each term integrated correctly)",
    tier: "Higher",
    level: "A-Level",
    topic: "Calculus",
    learningObjective: "Apply power rule to integrate polynomial functions",
    calculatorAllowed: false,
    difficulty: 3,
    marks: 3,
  },
  {
    id: "Q011",
    questionText: "Pythagoras' theorem: A right-angled triangle has sides of 5cm and 12cm. Calculate the hypotenuse.",
    markSchemeText: "c² = a² + b² = 5² + 12² = 25 + 144 = 169. c = √169 = 13cm. (2 marks: 1 for formula, 1 for answer)",
    tier: "Foundation",
    level: "GCSE",
    topic: "Geometry",
    learningObjective: "Apply Pythagoras' theorem to find the hypotenuse",
    calculatorAllowed: true,
    difficulty: 2,
    marks: 2,
  },
  {
    id: "Q012",
    questionText: "Express 0.36̇ as a fraction in its simplest form.",
    markSchemeText: "Let x = 0.36̇. 100x = 36.36̇. 100x - x = 36. 99x = 36. x = 36/99 = 4/11. (3 marks: 1 for method, 1 for equation, 1 for simplification)",
    tier: "Higher",
    level: "GCSE",
    topic: "Number",
    learningObjective: "Convert recurring decimals to fractions",
    calculatorAllowed: false,
    difficulty: 4,
    marks: 3,
  },
]
